import type { Product, Allergen, User, Diet, HealthGoal } from './types';
import {
  GlutenIcon,
  DairyIcon,
  NutsIcon,
  SoyIcon,
  EggsIcon,
  FishIcon,
  ShellfishIcon,
  MilkIcon,
  VegetarianIcon,
  VeganIcon,
  PescatarianIcon,
  KetoIcon,
  PaleoIcon,
  LoseWeightIcon,
  BuildMuscleIcon,
  ReduceSugarIcon,
  IncreaseFiberIcon,
  HeartHealthIcon,
  EatCleanIcon,
} from '@/components/icons/food-icons';


export const ALL_PRODUCTS: Product[] = [
  {
    id: '1',
    barcode: '9300652012979',
    name: 'Organic Granola',
    brand: 'Nature\'s Path',
    imageUrl: 'https://picsum.photos/seed/p1/400/400',
    imageHint: 'granola bowl',
    suitability: 'recommended',
    tags: ['organic', 'high_fiber'],
    ingredients: 'Whole grain rolled oats, cane sugar, soy oil, brown rice flour, flax seeds, oat syrup solids, sea salt, molasses.',
    allergens: ['soy', 'gluten'],
    nutritionalInformation: {
      servingsPerPackage: 7,
      servingSize: '55g',
      metrics: [
        { name: 'Energy', perServing: '1050 kJ', per100g: '1910 kJ' },
        { name: 'Protein', perServing: '5.5g', per100g: '10g' },
        { name: 'Fat, total', perServing: '9.4g', per100g: '17.1g' },
        { name: '- saturated', perServing: '1.4g', per100g: '2.5g' },
        { name: 'Carbohydrate', perServing: '33.6g', per100g: '61g' },
        { name: '- sugars', perServing: '9.9g', per100g: '18g' },
        { name: 'Sodium', perServing: '77mg', per100g: '140mg' },
      ],
    },
  },
  {
    id: '2',
    barcode: '028400070794',
    name: 'Spicy Tortilla Chips',
    brand: 'Doritos',
    imageUrl: 'https://picsum.photos/seed/p2/400/400',
    imageHint: 'tortilla chips',
    suitability: 'caution',
    tags: ['high_sodium', 'processed'],
    ingredients: 'Corn, Vegetable Oil (Corn, Canola, and/or Sunflower Oil), Maltodextrin (Made from Corn), Salt, Cheddar Cheese (Milk, Cheese Cultures, Salt, Enzymes), Whey, Monosodium Glutamate, Buttermilk, Romano Cheese (Part-Skim Cow\'s Milk, Cheese Cultures, Salt, Enzymes), Whey Protein Concentrate, Onion Powder, Corn Flour, Natural and Artificial Flavor, Dextrose, Tomato Powder, Lactose, Spices, Artificial Color (Yellow 6, Yellow 5, Red 40), Lactic Acid, Citric Acid, Sugar, Garlic Powder, Skim Milk, Red and Green Bell Pepper Powder, Disodium Inosinate, Disodium Guanylate.',
    allergens: ['milk'],
    nutritionalInformation: {
      servingsPerPackage: 10,
      servingSize: '28g',
      metrics: [
        { name: 'Energy', perServing: '630 kJ', per100g: '2250 kJ' },
        { name: 'Protein', perServing: '2g', per100g: '7.1g' },
        { name: 'Fat, total', perServing: '8g', per100g: '28.6g' },
        { name: '- saturated', perServing: '1g', per100g: '3.6g' },
        { name: 'Carbohydrate', perServing: '18g', per100g: '64.3g' },
        { name: '- sugars', perServing: '1g', per100g: '3.6g' },
        { name: 'Sodium', perServing: '210mg', per100g: '750mg' },
      ],
    },
  },
  {
    id: '3',
    barcode: '016000124687',
    name: 'Sugary Cereal',
    brand: 'Lucky Charms',
    imageUrl: 'https://picsum.photos/seed/p3/400/400',
    imageHint: 'cereal bowl',
    suitability: 'not_recommended',
    tags: ['high_sugar', 'processed', 'kids'],
    ingredients: 'Whole Grain Oats, Sugar, Corn Starch, Modified Corn Starch, Corn Syrup, Dextrose, Salt, Gelatin, Trisodium Phosphate, Red 40, Yellow 5 & 6, Blue 1, Natural and Artificial Flavor, Vitamin E (mixed tocopherols).',
    allergens: ['gluten'],
    nutritionalInformation: {
      servingsPerPackage: 8,
      servingSize: '36g',
      metrics: [
        { name: 'Energy', perServing: '586 kJ', per100g: '1628 kJ' },
        { name: 'Protein', perServing: '2g', per100g: '5.6g' },
        { name: 'Fat, total', perServing: '1.5g', per100g: '4.2g' },
        { name: '- saturated', perServing: '0g', per100g: '0g' },
        { name: 'Carbohydrate', perServing: '30g', per100g: '83.3g' },
        { name: '- sugars', perServing: '12g', per100g: '33.3g' },
        { name: 'Sodium', perServing: '200mg', per100g: '555mg' },
      ],
    },
  },
  {
    id: '4',
    barcode: '723456789019',
    name: 'Plain Greek Yogurt',
    brand: 'Fage',
    imageUrl: 'https://picsum.photos/seed/p4/400/400',
    imageHint: 'greek yogurt',
    suitability: 'recommended',
    tags: ['high_protein', 'probiotics'],
    ingredients: 'Grade A Pasteurized Skimmed Milk and Cream, Live Active Yogurt Cultures (L. Bulgaricus, S. Thermophilus, L. Acidophilus, Bifidus, L. Casei).',
    allergens: ['milk'],
    nutritionalInformation: {
      servingsPerPackage: 1,
      servingSize: '170g',
      metrics: [
        { name: 'Energy', perServing: '397 kJ', per100g: '234 kJ' },
        { name: 'Protein', perServing: '18g', per100g: '10.6g' },
        { name: 'Fat, total', perServing: '0g', per100g: '0g' },
        { name: '- saturated', perServing: '0g', per100g: '0g' },
        { name: 'Carbohydrate', perServing: '6g', per100g: '3.5g' },
        { name: '- sugars', perServing: '6g', per100g: '3.5g' },
        { name: 'Sodium', perServing: '65mg', per100g: '38mg' },
      ],
    },
  },
  {
    id: '5',
    barcode: '890123456789',
    name: 'Dark Chocolate 85%',
    brand: 'Green & Black\'s',
    imageUrl: 'https://picsum.photos/seed/p5/400/400',
    imageHint: 'dark chocolate',
    suitability: 'recommended',
    tags: ['organic', 'antioxidants'],
    ingredients: 'Cocoa Mass, Cane Sugar, Cocoa Butter, Vanilla Extract.',
    allergens: [],
    nutritionalInformation: {
      servingsPerPackage: 5,
      servingSize: '20g',
      metrics: [
        { name: 'Energy', perServing: '519 kJ', per100g: '2595 kJ' },
        { name: 'Protein', perServing: '2.2g', per100g: '11g' },
        { name: 'Fat, total', perServing: '10.6g', per100g: '53g' },
        { name: '- saturated', perServing: '6.4g', per100g: '32g' },
        { name: 'Carbohydrate', perServing: '3.0g', per100g: '15g' },
        { name: '- sugars', perServing: '2.8g', per100g: '14g' },
        { name: 'Sodium', perServing: '<1mg', per100g: '<5mg' },
      ],
    },
  },
  {
    id: '6',
    barcode: '049000000469',
    name: 'Classic Cola',
    brand: 'Coca-Cola',
    imageUrl: 'https://picsum.photos/seed/p6/400/400',
    imageHint: 'soda can',
    suitability: 'not_recommended',
    tags: ['high_sugar', 'caffeine'],
    ingredients: 'Carbonated Water, High Fructose Corn Syrup, Caramel Color, Phosphoric Acid, Natural Flavors, Caffeine.',
    allergens: [],
    nutritionalInformation: {
      servingsPerPackage: 1,
      servingSize: '355ml',
      metrics: [
        { name: 'Energy', perServing: '586 kJ', per100g: '165 kJ' },
        { name: 'Protein', perServing: '0g', per100g: '0g' },
        { name: 'Fat, total', perServing: '0g', per100g: '0g' },
        { name: '- saturated', perServing: '0g', per100g: '0g' },
        { name: 'Carbohydrate', perServing: '39g', per100g: '11g' },
        { name: '- sugars', perServing: '39g', per100g: '11g' },
        { name: 'Sodium', perServing: '45mg', per100g: '13mg' },
      ],
    },
  }
];

export const AVAILABLE_ALLERGENS: Allergen[] = [
  { id: 'gluten', name: 'Gluten', icon: GlutenIcon },
  { id: 'dairy', name: 'Dairy', icon: DairyIcon },
  { id: 'nuts', name: 'Nuts', icon: NutsIcon },
  { id: 'soy', name: 'Soy', icon: SoyIcon },
  { id: 'eggs', name: 'Eggs', icon: EggsIcon },
  { id: 'fish', name: 'Fish', icon: FishIcon },
  { id: 'shellfish', name: 'Shellfish', icon: ShellfishIcon },
  { id: 'milk', name: 'Milk', icon: MilkIcon },
];

export const AVAILABLE_DIETS: Diet[] = [
    { id: 'vegetarian', name: 'Vegetarian', icon: VegetarianIcon },
    { id: 'vegan', name: 'Vegan', icon: VeganIcon },
    { id: 'pescatarian', name: 'Pescatarian', icon: PescatarianIcon },
    { id: 'gluten_free', name: 'Gluten-Free', icon: GlutenIcon },
    { id: 'keto', name: 'Keto', icon: KetoIcon },
    { id: 'paleo', name: 'Paleo', icon: PaleoIcon },
];

export const AVAILABLE_HEALTH_GOALS: HealthGoal[] = [
    { id: 'lose_weight', name: 'Lose Weight', icon: LoseWeightIcon },
    { id: 'build_muscle', name: 'Build Muscle', icon: BuildMuscleIcon },
    { id: 'reduce_sugar', name: 'Reduce Sugar', icon: ReduceSugarIcon },
    { id: 'increase_fiber', name: 'Increase Fiber', icon: IncreaseFiberIcon },
    { id: 'heart_health', name: 'Heart Health', icon: HeartHealthIcon },
    { id: 'eat_clean', name: 'Eat Clean', icon: EatCleanIcon },
];

export const MOCK_USER: User = {
  name: 'Alex Doe',
  email: 'alex.doe@example.com',
  avatarUrl: 'https://picsum.photos/seed/user/100/100',
  avatarHint: 'person smiling',
  allergies: ['nuts', 'shellfish'],
  diet: ['vegetarian'],
  healthGoals: ['reduce_sugar'],
  shoppingList: ['1', '4'],
  scanHistory: ['3', '2', '1', '5'],
};

export const MOCK_USERS: User[] = [
    MOCK_USER,
    {
      name: 'Jane Smith',
      email: 'jane.smith@example.com',
      avatarUrl: 'https://picsum.photos/seed/jane/100/100',
      avatarHint: 'woman smiling',
      allergies: ['gluten', 'dairy'],
      diet: [],
      healthGoals: [],
      shoppingList: ['4', '5'],
      scanHistory: ['6', '1'],
    }
]
